FROM centos:7

# Install stuff for libsmi build and FPM.
RUN yum -y install git libtool flex bison tar gzip make gcc rpm-build ruby-devel rpm-build rubygems \
    && gem install --no-document git -v 1.7.0 \
    && gem install --no-document fpm -v 1.12.0

RUN groupadd -f -g %GID% build
RUN useradd -d /home/build -m -s /bin/bash -u %UID% -g %GID% build 
RUN echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
USER build
