FROM centos:7

RUN groupadd -f -g %GID% build; \
    useradd -d /home/build -m -s /bin/bash -u %UID% -g %GID% build; \
    echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install stuff for libsmi build and FPM.
RUN yum -y install git libtool wget flex bison tar gzip make gcc rpm-build ruby-devel rpm-build rubygems

RUN gem install --no-document git -v 1.7.0; \
    gem install --no-document backports -v 3.21.0; \
    gem install --no-document fpm -v 1.12.0; \
	fpm --help

USER build
